@ProgressiveLoadBackend_HostAddress = https://localhost:7295

GET {{ProgressiveLoadBackend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ProgressiveLoadBackend_HostAddress}}/api/users/register
Content-Type: application/json

{
  //RegisterDTO
}

###
